name: 'A11y AI Action'
description: 'Experimental tool to automatically detect accessibility issues in web pages and provide suggestions for fixing them.'
author: 'sinedied'
branding:
  icon: 'user-check'
  color: 'purple'
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  files:
    description: 'One or more glob patterns of files to include.'
    required: false
    default: '**/*.html'
  # github_token:
  #   description: 'GitHub access token to comment on pull requests. Defaults to {{ github.token }}.'
  #   required: false
  #   default: ${{ github.token }}
  # pull_request:
  #   description: 'Propose changes as a pull request'
  #   required: false
  #   default: false
  # branch:
  #   description: 'The git branch to use'
  #   required: false
  #   default: 'main'
  # conventional_commits:
  #   description: 'Use conventional commits messages'
  #   required: false
  #   default: false
outputs:
  report_file:
    description: 'Path to the generated report file'
  report_html:
    description: 'The report in HTML format'
  report_md:
    description: 'The report in markdown format'
